---
- name: deployment
  hosts: all
  become: true
  vars:
    nexus_url: ec2-13-210-72-40.ap-southeast-2.compute.amazonaws.com:8081/repository
    repository_type: java-maven-war-appD-release
    group_id: com%2Fmycompany%2Fapp
    artifact_id: hello-world-war
    version: 1.0.3
    build_number: "{{build_number}}"
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: "{{nexus_url}}/{{repository_type}}/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war"
      dest: /home/ec2-user
      username: admin
      password: admin

  - name: Rename war file
    ansible.builtin.shell: mv /home/ec2-user/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war /home/ec2-user/faangler.war

  - name: Deploying artifact in webapps
    ansible.builtin.shell: cp /home/ec2-user/faangler.war /opt/apache-tomcat-9.0.84/webapps/faangler.war

  - name: remove the artifact
    ansible.builtin.shell: rm -rf /home/ec2-user/faangler.war
